name: Unity Android APK Build
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: buildalon/unity-setup@v2
        with:
          version-file: 'ProjectSettings/ProjectVersion.txt'
          build-targets: Android
      - uses: buildalon/activate-unity-license@v2
        with:
          license: 'Personal'
          username: ${{ secrets.UNITY_USERNAME }}
          password: ${{ secrets.UNITY_PASSWORD }}
      - uses: buildalon/unity-action@v1
        name: Build Android
        with:
          build-target: Android
          args: '-quit -batchmode -buildTarget Android'
      - uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: '**/*.apk'
